### ISSUE TITLE
Three more questions from Codility 

### ISSUE THREAD

**Issue by larytet** [johnmee/codility#12]
Unfortunately only screenshots
https://github.com/larytet-py/codility
I wonder how to solve the following
N integers in array of [1..N]  In one move you inc/dec the value by 1
After every move all number should remain within [1..N]
What is the smallest number of steps to make all values distinct?
[1,2,1] can be changed in 2 steps [1,2,2], [1,2,3]
[6,2,3,5,6,3] 4 steps [6,2,1,5,3]

My idea was https://github.com/larytet-py/codility/blob/main/distinct-integers.py

**Comment by johnmee** [comment]
Interesting.  One wonders if the last example is correctly transcribed from the source, since the start array has six elements, but the supposed solution has only five, and I see nothing about removing elements of the array.  But I get the gist of the problem.
Send me a PR if you come up with a tidy solution.
